name: my_first_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  provider: ^6.0.0
  path: ^1.8.0

  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  url_launcher: ^6.1.12
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Forktune.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/team/
    - assets/images/
    - assets/images/launch_image.png
    - assets/images/leaf1.png
    - assets/images/leaf2.png
    - assets/images/leaf3.png
    - assets/images/cloud1.png
    - assets/images/cabbage.png
    - assets/images/cauliflower.png
    - assets/images/pan2.png
    - assets/signup.jpg
