name: my_first_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Forktune.png"

flutter:
  uses-material-design: true

  assets:
    - assets/team/
    - assets/images/launch_image.png
